# Exercise 3: A City Divided

#### Dataset: `The_Outbreak_of_1849.csv`

19th Century London was divided into districts, much like Chicago is divided into neighborhoods. These districts were grouped by geography, just like Chicago (South Side, North Side, West side, Far South Side, etc.)

<img src="https://i2.wp.com/londontopia.net/wp-content/uploads/2014/08/london-county.jpg" width=600>

**Which London districts had the highest death rates between between 1840 and 1854?**

In [1]:
import pandas as pd

In [3]:
Outbreak = pd.read_csv("The_Outbreak_of_1849.csv")
Outbreak

,District,Region,Population (1851),Deaths from Cholera (1849),Death Rate (per 1000),Area,Elevation,Houses,Value of Houses,Water Supplier
0,Kensington,West,120004,206,1.716609,7374,40,10962.0,488188,Chelsea_GrandJunction_WestMisslesex
1,Chelsea,West,56538,247,4.368743,865,12,5648.0,169679,Chelsea
2,St. George Hanover Square,West,73230,131,1.788884,1161,34,7630.0,878690,GrandJunction
3,Westminster,West,65609,437,6.660672,917,3,6439.0,238164,Chelsea
4,St. Martin-in-the-Fields,West,24640,91,3.693182,305,38,2439.0,297665,NewRiver
5,St. James Westminster,West,36406,57,1.565676,164,58,3590.0,474528,GrandJunction_NewRiver
6,Marylebone,North,157696,261,1.655083,1509,87,14169.0,1050664,WestMisslesex
7,Hampstead,North,11986,9,0.750876,2252,350,1411.0,58743,Hampstead_WestMisslesex
8,Pancras,North,166956,360,2.156257,2716,73,14766.0,633974,Hampstead__NewRiver_WestMisslesex
9,Islington,North,95329,187,1.961628,3127,94,8508.0,307286,NewRiver
10,Hackney,North,58429,139,2.378956,3929,53,7192.0,186415,EastLondon_NewRiver
11,St. Giles,Central,54214,285,5.256945,245,68,4959.0,306439,NewRiver
12,Strand,Central,44460,156,3.508772,174,50,4327.0,321999,NewRiver
13,Holborn,Central,46621,161,3.453379,196,53,4603.0,261970,NewRiver
14,Clerkenwell,Central,64778,121,1.867918,315,65,6946.0,235324,NewRiver
15,St. Luke,Central,54055,183,3.385441,220,51,6385.0,186256,NewRiver
16,East London,Central,44406,182,4.098545,153,40,4796.0,191558,NewRiver
17,West London,Central,28790,429,14.901007,136,29,3010.0,217562,NewRiver
18,City of London,Central,55932,207,3.700923,434,31,7921.0,990008,NewRiver
19,Shoreditch,East,109257,830,7.596767,646,48,NaN,323091,EastLondon_NewRiver
20,Bethnal Green,East,90193,789,8.747907,760,38,11782.0,109937,EastLondon
21,Whitechapel,East,79759,506,6.344112,406,32,8834.0,243657,EastLondon
22,St. George-in-the-East,East,48376,199,4.113610,243,31,5985.0,196942,EastLondon
23,Stepney,East,110775,501,4.522681,1257,21,14364.0,301888,EastLondon
24,Poplar,East,47162,313,6.636699,2918,8,5066.0,229751,EastLondon
25,"St. Saviour, Southwark",South,35731,539,15.084940,250,3,4659.0,174732,Lambeth_SouthwarkVauxhall
26,"St. Olave, Southwark",South,19375,349,18.012903,169,4,2523.0,90583,SouthwarkVauxhall
27,Bermondsey,South,48128,734,15.250997,688,0,5674.0,107821,SouthwarkVauxhall
28,St. George Southwark,South,51824,836,16.131522,282,0,6663.0,155175,Lambeth_SouthwarkVauxhall
29,Newington,South,64816,907,13.993458,624,-1,9370.0,207460,Lambeth_SouthwarkVauxhall
30,Lambeth,South,139325,1618,11.613135,4015,3,17791.0,510341,Lambeth_SouthwarkVauxhall
31,Wandsworth,South,50764,484,9.534316,11695,24,6459.0,193395,SouthwarkVauxhall
32,Camberwell,South,54667,504,9.219456,4342,4,6843.0,180418,Lambeth_SouthwarkVauxhall
33,Rotherhithe,South,17805,352,19.769728,886,0,2420.0,59072,Kent_SouthwarkVauxhall
34,Greenwich,South,99305,718,7.230250,5367,8,11995.0,274478,Kent
35,Lewisham,South,34835,96,2.755849,17224,28,3966.0,111357,Kent

**Use some code from `JS_Exercise_1.ipynb` to calculate the death rate for the districts and add it as a new column. You can copy and paste but will have to make some changes.**

### Are there certain districts that were impacted by cholera more than others?